// ── Config ──────────────────────────────────────────────
let config = null;

// ── App state ───────────────────────────────────────────
const state = {
  key: "C",
  scale: "major",
  octave: 4,
  wave: "sine",
  slots: [],          // array of 10 chord slot objects
  activeSlot: null,   // currently gestured slot (highlighted, not playing)
  playingSlot: null,  // currently playing slot
  volume: 0.7,
};

// ── DOM refs ─────────────────────────────────────────────
const video    = document.getElementById("video");
const canvas   = document.getElementById("canvas");
const ctx      = canvas.getContext("2d");
const status   = document.getElementById("status");

// ── MediaPipe Hands ───────────────────────────────────────
let hands = null;
let latestHandResults = null;
let prevConfirmGesture = false;
let lastConfirmTime = 0;
const CONFIRM_COOLDOWN_MS = 100;

function initMediaPipe() {
  hands = new Hands({
    locateFile: (file) => `https://cdn.jsdelivr.net/npm/@mediapipe/hands/${file}`
  });

  hands.setOptions({
    maxNumHands: 2,
    modelComplexity: 1,
    minDetectionConfidence: 0.7,
    minTrackingConfidence: 0.6,
  });

  hands.onResults((results) => {
    latestHandResults = results;
  });
}

// ── Boot ─────────────────────────────────────────────────
async function boot() {

  status.textContent = "Loading config...";

  // Load config.json generated by Python
  const res = await fetch("/config");
  config = await res.json();

  status.textContent = "Starting camera...";
  await startCamera();

  status.textContent = "Initialising hand detection...";
  initMediaPipe();

  status.textContent = "Ready";
  status.className = "ready";
  loop();

  buildChordSlots();
}

// ── Camera ───────────────────────────────────────────────
async function startCamera() {
  const stream = await navigator.mediaDevices.getUserMedia({
    video: { width: 1280, height: 720, facingMode: "user" },
    audio: false,
  });
  video.srcObject = stream;

  // Wait for video to be ready
  await new Promise(resolve => video.onloadedmetadata = resolve);

  // Match canvas size to the actual rendered size of the container
  const rect = video.getBoundingClientRect();
  canvas.width  = rect.width;
  canvas.height = rect.height;
}

// ── Star field ────────────────────────────────────────────
const stars = Array.from({ length: 350 }, () => ({
  x:       Math.random() * window.innerWidth,
  y:       Math.random() * window.innerHeight,
  radius:  Math.random() * 1.0 + 0.3,
  opacity: Math.random() * 0.8 + 0.3,
  twinkle: Math.random() * 0.025 + 0.003,  // wider speed range
  phase:   Math.random() * Math.PI * 2,
  style:   Math.floor(Math.random() * 3),   // 0=sine, 1=random flicker, 2=steady
}));

function drawStars() {
  stars.forEach(star => {
    star.phase += star.twinkle;
    
    let op;
    if (star.style === 0) {
      // smooth sine twinkle
      op = star.opacity * (0.6 + 0.4 * Math.sin(star.phase));
    } else if (star.style === 1) {
      // occasional random flicker
      op = star.opacity * (Math.random() > 0.98 ? 0.2 : 1.0);
    } else {
      // mostly steady with very subtle drift
      op = star.opacity * (0.85 + 0.15 * Math.sin(star.phase * 0.3));
    }

    ctx.beginPath();
    ctx.arc(star.x, star.y, star.radius, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(255, 255, 255, ${op})`;
    ctx.fill();
  });
}

// ── Particle trails ───────────────────────────────────────
const FINGERTIP_INDICES = [4, 8, 12, 16, 20]; // thumb, index, middle, ring, pinky

const trails = {
  Left:  Array.from({ length: 5 }, () => []),
  Right: Array.from({ length: 5 }, () => []),
};

function updateTrails(landmarks, handLabel) {
  if (!landmarks || landmarks.length < 21) return;
  const { renderWidth, renderHeight, offsetX, offsetY } = getVideoRenderRect();

  FINGERTIP_INDICES.forEach((tipIndex, i) => {
    const lm = landmarks[tipIndex];
    const x = offsetX + (1 - lm.x) * renderWidth;
    const y = offsetY + lm.y * renderHeight;

    // Only spawn particles if fingertip moved enough
    const trail = trails[handLabel][i];
    const last = trail[trail.length - 1];
    const moved = !last || Math.hypot(x - last.x, y - last.y) > 3;

    if (moved) {
      for (let j = 0; j < 2; j++) {
        trail.push({
          x: x + (Math.random() - 0.5) * 8,
          y: y + (Math.random() - 0.5) * 8,
          vx: (Math.random() - 0.5) * 1.2,
          vy: -Math.random() * 0.8,
          life: 1.0,
          size: Math.random() * 1.8 + 0.4,
        });
      }
    }

    if (trail.length > 40) {
      trails[handLabel][i] = trail.slice(-40);
    }
  });
}

function drawTrails(handLabel) {
  const color = "255, 255, 255";  // same for both hands

  trails[handLabel].forEach((trail, i) => {
    trail.forEach(p => {
      // Move particle
      p.x  += p.vx;
      p.y  += p.vy;
      p.life -= 0.04;   // fade out over ~25 frames

      if (p.life <= 0) return;

      ctx.beginPath();
      ctx.arc(p.x, p.y, p.size * p.life, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(${color}, ${p.life * 0.9})`;
      ctx.fill();
    });

    // Remove dead particles
    trails[handLabel][i] = trail.filter(p => p.life > 0);
  });
}

// ── Hand skeleton ─────────────────────────────────────────
function getVideoRenderRect() {
  const videoAspect = video.videoWidth / video.videoHeight;
  const canvasAspect = canvas.width / canvas.height;

  let renderWidth, renderHeight, offsetX, offsetY;

  if (videoAspect > canvasAspect) {
    renderWidth  = canvas.width;
    renderHeight = canvas.width / videoAspect;
    offsetX      = 0;
    offsetY      = (canvas.height - renderHeight) / 2;
  } else {
    renderWidth  = canvas.height * videoAspect;
    renderHeight = canvas.height;
    offsetX      = (canvas.width - renderWidth) / 2;
    offsetY      = 0;
  }

  return { renderWidth, renderHeight, offsetX, offsetY };
}

// MediaPipe hand connections — pairs of landmark indices to draw lines between
const HAND_CONNECTIONS = [
  [0,1],[1,2],[2,3],[3,4],         // thumb
  [0,5],[5,6],[6,7],[7,8],         // index
  [0,9],[9,10],[10,11],[11,12],    // middle
  [0,13],[13,14],[14,15],[15,16],  // ring
  [0,17],[17,18],[18,19],[19,20],  // pinky
  [5,9],[9,13],[13,17],            // palm
];

function drawSkeleton(landmarks, handLabel) {
  if (!landmarks || landmarks.length < 21) return;
  const { renderWidth, renderHeight, offsetX, offsetY } = getVideoRenderRect();

  const toPixel = (lm) => ({
    x: offsetX + (1 - lm.x) * renderWidth,
    y: offsetY + lm.y * renderHeight,
  });

  // Right hand violet, left hand blue
  const connectionColor = handLabel === "Left"
    ? "rgba(109, 40, 217, 0.9)"    // deep purple
    : "rgba(29, 78, 216, 0.9)";    // deep blue

  const jointColor = handLabel === "Left"
    ? "rgba(192, 132, 252, 0.95)"    // soft luminous violet
    : "rgba(96, 165, 250, 0.95)";    // soft luminous blue

  // Draw connections
  ctx.lineWidth = 2;
  ctx.strokeStyle = connectionColor;

  for (const [a, b] of HAND_CONNECTIONS) {
    const pA = toPixel(landmarks[a]);
    const pB = toPixel(landmarks[b]);
    ctx.beginPath();
    ctx.moveTo(pA.x, pA.y);
    ctx.lineTo(pB.x, pB.y);
    ctx.stroke();
  }

  // Draw joints
  for (const lm of landmarks) {
    const p = toPixel(lm);
    ctx.beginPath();
    ctx.arc(p.x, p.y, 4, 0, Math.PI * 2);
    ctx.fillStyle = jointColor;
    ctx.fill();
  }
}

// ── Gesture handling ──────────────────────────────────────

function setActiveSlot(index) {
  // Remove active class from all slots
  for (let i = 0; i < 10; i++) {
    const input = document.getElementById(`root-${i}`);
    const typeEl = document.getElementById(`type-${i}`);
    const invEl = document.getElementById(`inv-${i}`);
    if (input) input.classList.remove("active");
    if (typeEl) typeEl.classList.remove("active");
    if (invEl) invEl.classList.remove("active");
  }

  // Add active class to targeted slot
  if (index !== null && index >= 0 && index < 10) {
    const input = document.getElementById(`root-${index}`);
    const typeEl = document.getElementById(`type-${index}`);
    const invEl = document.getElementById(`inv-${index}`);
    if (input) input.classList.add("active");
    if (typeEl) typeEl.classList.add("active");
    if (invEl) invEl.classList.add("active");
  }
}

function onConfirm() {
  if (state.activeSlot === null) return;
//   if (state.activeSlot === state.playingSlot) return;
  const slot = state.slots[state.activeSlot];
  if (!slot || !slot.root) return;

  // Update playing slot
  state.playingSlot = state.activeSlot;

  // Update now playing display
  const chordDisplay = document.getElementById("chord-display");
  if (chordDisplay) {
    chordDisplay.textContent = slot.display || `${slot.root}${slot.chordType}`;
    chordDisplay.classList.add("playing");
  }

  // Highlight playing slot
  setPlayingSlot(state.playingSlot);

  playChord(slot);
  console.log("Playing:", slot.display, "inversion:", slot.inversion); 
}

function setPlayingSlot(index) {
  // Remove playing class from all slots
  for (let i = 0; i < 10; i++) {
    const input = document.getElementById(`root-${i}`);
    const typeEl = document.getElementById(`type-${i}`);
    const invEl = document.getElementById(`inv-${i}`);
    if (input) input.classList.remove("playing");
    if (typeEl) typeEl.classList.remove("playing");
    if (invEl) invEl.classList.remove("playing");
  }

//   if (index !== null && index >= 0 && index < 10) {
//     const input = document.getElementById(`root-${index}`);
//     const typeEl = document.getElementById(`type-${index}`);
//     const invEl = document.getElementById(`inv-${index}`);
//     if (input) input.classList.add("playing");
//     if (typeEl) typeEl.classList.add("playing");
//     if (invEl) invEl.classList.add("playing");
//   }
}

function onStop() {
  state.playingSlot = null;
  state.activeSlot = null;

  const chordDisplay = document.getElementById("chord-display");
  if (chordDisplay) {
    chordDisplay.textContent = "—";
    chordDisplay.classList.remove("playing");
  }

  setActiveSlot(null);
  setPlayingSlot(null);

  stopAudio();
  console.log("Stopped");
}

// ── Chord slots UI ────────────────────────────────────────
function buildChordSlots() {
  const container = document.getElementById("chord-slots");
  container.innerHTML = "";
  state.slots = [];

  const chords = config.slots || [];

  // Build state
  for (let i = 0; i < 10; i++) {
    const chord = chords[i] || null;
    state.slots.push({
      index:     i,
      root:      chord ? chord.root : "",
      chordType: chord ? chord.chord_type : "maj",
      inversion: chord ? (chord.inversion || 0) : 0,
      octave: chord ? (chord.octave ?? config.octave ?? 4) : (config.octave ?? 4),
      display:   chord ? chord.display : null,
    });
  }

  // Row 1 — root inputs
  const rootRow = document.createElement("div");
  rootRow.className = "slots-row";
  for (let i = 0; i < 10; i++) {
    const cell = document.createElement("div");
    cell.className = "slot-cell";
    const input = document.createElement("input");
    input.type = "text";
    input.className = "slot-root-input";
    input.id = `root-${i}`;
    input.value = state.slots[i].root;
    input.maxLength = 2;
    input.placeholder = "";
    input.autocomplete = "off";
    // input.addEventListener("change", (e) => onRootChange(i, e.target.value));
    cell.appendChild(input);
    rootRow.appendChild(cell);
  }

  // Row 2 — chord type dropdowns
  const typeRow = document.createElement("div");
  typeRow.className = "slots-row";
  for (let i = 0; i < 10; i++) {
    const cell = document.createElement("div");
    cell.className = "slot-cell";
    const select = document.createElement("select");
    select.className = "slot-select";
    select.id = `type-${i}`;
    if (state.slots[i].root) {
        config.chord_types.forEach(t => {
            const opt = document.createElement("option");
            opt.value = t;
            opt.textContent = t;
            if (t === state.slots[i].chordType) opt.selected = true;
            select.appendChild(opt);
        });
    } else {
        const opt = document.createElement("option");
        opt.value = "";
        opt.textContent = "";
        select.appendChild(opt);
    }
    // config.chord_types.forEach(t => {
    //   const opt = document.createElement("option");
    //   opt.value = t;
    //   opt.textContent = t;
    //   if (t === state.slots[i].chordType) opt.selected = true;
    //   select.appendChild(opt);
    // });
    // select.addEventListener("change", (e) => onTypeChange(i, e.target.value));
    cell.appendChild(select);
    typeRow.appendChild(cell);
  }

  // Row 3 — inversion dropdowns
  const invRow = document.createElement("div");
  invRow.className = "slots-row";
  for (let i = 0; i < 10; i++) {
    const cell = document.createElement("div");
    cell.className = "slot-cell";
    const select = document.createElement("select");
    select.className = "slot-select";
    select.id = `inv-${i}`;
    // Default inversion options — updated dynamically when chord changes
    ["root"].forEach((label, idx) => {
      const opt = document.createElement("option");
      opt.value = idx;
      opt.textContent = label;
      select.appendChild(opt);
    });
    // select.addEventListener("change", (e) => onInversionChange(i, parseInt(e.target.value)));
    cell.appendChild(select);
    invRow.appendChild(cell);
  }

  // Row 4 — gesture numbers
  const gestureRow = document.createElement("div");
  gestureRow.className = "slots-row";
  for (let i = 0; i < 10; i++) {
    const cell = document.createElement("div");
    cell.className = "slot-cell";
    const label = document.createElement("span");
    label.className = "slot-gesture-label";
    label.textContent = i + 1;
    cell.appendChild(label);
    gestureRow.appendChild(cell);
  }

  container.appendChild(rootRow);
  container.appendChild(typeRow);
  container.appendChild(invRow);
  container.appendChild(gestureRow);

  // Populate inversion dropdowns with actual note names
  for (let i = 0; i < 10; i++) {
    updateInversionOptions(i);
  }
}

// function onRootChange(slotIndex, value) {
//   state.slots[slotIndex].root = value.trim();
//   updateInversionOptions(slotIndex);
// }

// function onTypeChange(slotIndex, value) {
//   state.slots[slotIndex].chordType = value;
//   updateInversionOptions(slotIndex);
// }

// function onInversionChange(slotIndex, value) {
//   state.slots[slotIndex].inversion = value;
// }

function updateInversionOptions(slotIndex) {
  const select = document.getElementById(`inv-${slotIndex}`);
  if (!select) return;
  select.innerHTML = "";

  const root = state.slots[slotIndex].root;
  const type = state.slots[slotIndex].chordType;

  if (!root) {
    const opt = document.createElement("option");
    opt.value = 0; opt.textContent = "";
    select.appendChild(opt);
    return;
  }

  const notes = getChordNoteNames(root, type);
  notes.forEach((note, idx) => {
    const opt = document.createElement("option");
    opt.value = idx;
    opt.textContent = note;
    if (idx === state.slots[slotIndex].inversion) opt.selected = true;
    select.appendChild(opt);
  });
}

// ── Music theory helpers ──────────────────────────────────
const SHARPS = ["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
const FLATS  = ["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"];

const CHORD_FORMULAS = {
  "maj":  [0,4,7],  "min":  [0,3,7],  "dim":  [0,3,6],
  "aug":  [0,4,8],  "maj7": [0,4,7,11], "7":  [0,4,7,10],
  "min7": [0,3,7,10], "dim7": [0,3,6,9],
  "sus2": [0,2,7],  "sus4": [0,5,7],  "add9": [0,4,7,14],
};

function getChordNoteNames(root, chordType) {
  const useFlats = root.includes("b") || root === "F";
  const noteList = useFlats ? FLATS : SHARPS;
  const rootIdx  = noteList.indexOf(root);
  if (rootIdx === -1) return [root];
  return (CHORD_FORMULAS[chordType] || [0,4,7])
    .map(i => noteList[(rootIdx + i) % 12]);
}

// ── Start ─────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", () => {
  boot();
});

// ── Render loop ───────────────────────────────────────────
async function loop() {
  // Feed current video frame to MediaPipe
  if (hands && video.readyState === 4) {
    await hands.send({ image: video });
  }

  // Clear canvas
  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // Draw stars
  drawStars();

  // Draw hands if detected
  if (latestHandResults && latestHandResults.multiHandLandmarks) {
  for (let i = 0; i < latestHandResults.multiHandLandmarks.length; i++) {
    const landmarks = latestHandResults.multiHandLandmarks[i];
    const handLabel = latestHandResults.multiHandedness[i].label;
    drawSkeleton(landmarks, handLabel);
    updateTrails(landmarks, handLabel);
    drawTrails(handLabel);
  }

  // ── Gesture detection ──────────────────────────────────
  const gestures = detectGestures(latestHandResults);

  // Pre-dwell highlight — show which slot is being targeted
  if (gestures.rawRightGesture !== undefined) {
        setActiveSlot(gestures.rawRightGesture - 1);
    } else {
        setActiveSlot(null);
    }

    // Confirmed slot selection after dwell
    if (gestures.slotIndex !== undefined) {
        state.activeSlot = gestures.slotIndex;
    }

    // Confirm/play
    if (gestures.confirm && !prevConfirmGesture) {
        const now = Date.now();
        if (now - lastConfirmTime > CONFIRM_COOLDOWN_MS) {
            lastConfirmTime = now;
            onConfirm();
        }
    }
    prevConfirmGesture = !!gestures.confirm;

    // Stop
    if (gestures.stop) {
        onStop();
    }
  }

  requestAnimationFrame(loop);
}